language: php

php:
  - 5.6
  - 7
  - 7.1

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $dependencies

script:
  - php -l src/*.php
