language: php

php:
  - "7.2"
  - "7.3"

matrix:
  include:
    - php: "7.2"
      env: dependencies="--prefer-lowest"
    - php: "7.3"
      env: CHECK_CODESTYLE=1
      before_install: phpenv config-rm xdebug.ini
      script:
        - composer analyze

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $DEPENDENCIES

script:
  - ./vendor/bin/phpunit
